version: "3.8"
services:

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8000:80

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env

  
